name: "Direct import & build inside Nixpkgs"

on:
  pull_request:
  push:
    branches:
      - master
  release:
    # created: a draft is saved, or a release or pre-release is published without previously being saved as a draft
    types: [ created ]

jobs:

  build10:
    name: "Clean integration test"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        packageRoot: [ hnix-store-core, hnix-store-remote ]
    defaults:
      run:
        working-directory: "./${{ matrix.packageRoot }}"
    steps:
    - name: "Git checkout"
      uses: actions/checkout@v2
    - name: "Local cache"
      uses: actions/cache@v2
      with:
        path: |
          /nix/store
        key: ${{ runner.os }}-Nixpkgs-integration-test
    - name: "Install Nix"
      uses: cachix/install-nix-action@v12
      with:
        nix_path: "nixpkgs=channel:nixos-unstable"
    - name: "Run Nixpkgs integration test"
      uses: Anton-Latukha/test-haskell-nixpkgs-integration-action@v1
